# Copyright (c) 2025, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# Expected input & output joint names following listed order for groot state/action space
joints:
  left_leg:
    - left_hip_pitch_joint
    - left_hip_roll_joint
    - left_hip_yaw_joint
    - left_knee_joint
    - left_ankle_pitch_joint
    - left_ankle_roll_joint
  right_leg:
    - right_hip_pitch_joint
    - right_hip_roll_joint
    - right_hip_yaw_joint
    - right_knee_joint
    - right_ankle_pitch_joint
    - right_ankle_roll_joint
  waist:
    - waist_yaw_joint
    - waist_roll_joint
    - waist_pitch_joint
  left_arm:
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_shoulder_yaw_joint
    - left_elbow_joint
    - left_wrist_roll_joint
    - left_wrist_pitch_joint
    - left_wrist_yaw_joint
  left_hand:
    - left_hand_index_0_joint
    - left_hand_index_1_joint
    - left_hand_middle_0_joint
    - left_hand_middle_1_joint
    - left_hand_thumb_0_joint
    - left_hand_thumb_1_joint
    - left_hand_thumb_2_joint
  right_arm:
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_shoulder_yaw_joint
    - right_elbow_joint
    - right_wrist_roll_joint
    - right_wrist_pitch_joint
    - right_wrist_yaw_joint
  right_hand:
    - right_hand_index_0_joint
    - right_hand_index_1_joint
    - right_hand_middle_0_joint
    - right_hand_middle_1_joint
    - right_hand_thumb_0_joint
    - right_hand_thumb_1_joint
    - right_hand_thumb_2_joint
