# This file shows how to configure the ReplayLerobotActionPolicy class for G1 locomanipulation task
dataset_path: /datasets/isaaclab_arena/locomanipulation_tutorial/arena_g1_loco_manipulation_dataset_generated/lerobot/
action_horizon: 16
embodiment_tag: new_embodiment
video_backend: decord
data_config: unitree_g1_sim_wbc

policy_joints_config_path: isaaclab_arena_gr00t/config/g1/gr00t_43dof_joint_space.yaml
action_joints_config_path: isaaclab_arena_gr00t/config/g1/43dof_joint_space.yaml
num_feedback_actions: 1
task_mode_name: g1_locomanipulation
