# This file shows how to configure the Gr00tClosedloopPolicy class for GR1 tabletop manipulation task
# TODO(xinjie.yao, 2025-10-07): change Hardcoded model_path to some releasable path
dataset_path: "/datasets/datasets/gr1_open_microwave/lerobot_gr1/lerobot_gr1/gr1_open_microwave_50_generated/lerobot"

action_horizon: 16
embodiment_tag: gr1
video_backend: decord
data_config: fourier_gr1_arms_only

policy_joints_config_path: isaaclab_arena_gr00t/config/gr1/gr00t_26dof_joint_space.yaml
action_joints_config_path: isaaclab_arena_gr00t/config/gr1/36dof_joint_space.yaml

num_feedback_actions: 1

task_mode_name: gr1_tabletop_manipulation
