# Copyright (c) 2025, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# This file shows how to configure the Gr00tClosedloopPolicy class for GR1 tabletop manipulation task
# NOTE(alexmillane, 2025-10-31): The model path here aligns with the model used in the static manipulation tutorial.
model_path: /models/isaaclab_arena/static_manipulation_tutorial/checkpoint-20000
language_instruction: "Reach out to the microwave and open it."
action_horizon: 16
embodiment_tag: gr1
video_backend: decord
data_config: fourier_gr1_arms_only

policy_joints_config_path: isaaclab_arena_gr00t/config/gr1/gr00t_26dof_joint_space.yaml
action_joints_config_path: isaaclab_arena_gr00t/config/gr1/36dof_joint_space.yaml
state_joints_config_path: isaaclab_arena_gr00t/config/gr1/54dof_joint_space.yaml
num_feedback_actions: 16
task_mode_name: gr1_tabletop_manipulation

pov_cam_name_sim: "robot_pov_cam_rgb"

original_image_size: [512, 512, 3]
target_image_size: [512, 512, 3]
