# Gr00tDatasetConfig Example Configuration
# This file shows how to configure the Gr00tDatasetConfig dataclass using YAML
# Example for G1 locomanipulation task

# Root directory for all data storage
data_root: "/datasets/isaaclab_arena/locomanipulation_tutorial"

# Instruction given to the policy in natural language
language_instruction: "Pick up the brown box from the shelf, and place it into the blue bin on the table located at the right of the shelf."
task_index: 2

# Name of the HDF5 file to use for the dataset
hdf5_name: "arena_g1_loco_manipulation_dataset_generated.hdf5"

# Mimic-generated HDF5 datafield names
state_name_sim: "robot_joint_pos"
left_eef_pos_name_sim: "left_eef_pos"
left_eef_quat_name_sim: "left_eef_quat"
right_eef_pos_name_sim: "right_eef_pos"
right_eef_quat_name_sim: "right_eef_quat"
teleop_base_height_command_name_sim: "base_height_cmd"
teleop_navigate_command_name_sim: "navigate_cmd"
teleop_torso_orientation_rpy_command_name_sim: "torso_orientation_rpy_cmd"
action_name_sim: "processed_actions"
pov_cam_name_sim: "robot_head_cam_rgb"

# Gr00t-LeRobot datafield names
state_name_lerobot: "observation.state"
action_name_lerobot: "action"
action_eef_name_sim: "action.eef"
video_name_lerobot: "observation.images.ego_view"
task_description_lerobot: "annotation.human.task_description"

# Parquet configuration
chunks_size: 1000

# Video configuration
fps: 50

# File path templates
data_path: "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet"
video_path: "videos/chunk-{episode_chunk:03d}/{video_key}/episode_{episode_index:06d}.mp4"

# Configuration file paths
modality_template_path: "isaaclab_arena_gr00t/config/g1/modality.json"
modality_fname: "modality.json"
episodes_fname: "episodes.jsonl"
tasks_fname: "tasks.jsonl"
info_template_path: "isaaclab_arena_gr00t/config/g1/info.json"
info_fname: "info.json"

# policy specific parameters (gr00t demonstration data stored in lerobot format)
policy_joints_config_path: "isaaclab_arena_gr00t/config/g1/gr00t_43dof_joint_space.yaml"
robot_type: "unitree_g1"

# Robot simulation specific parameters
action_joints_config_path: "isaaclab_arena_gr00t/config/g1/43dof_joint_space.yaml"
state_joints_config_path: "isaaclab_arena_gr00t/config/g1/43dof_joint_space.yaml"

# Image configuration (height, width, channels)
original_image_size: [480, 640, 3]
target_image_size: [480, 640, 3]
